### ISSUE TITLE
small clarification regarding model.r 

### ISSUE THREAD

**Issue by thestrawh8** [Rubikplayer/flame-fitting#1]
Hi, thanks for making it open. 
Before asking my doubt there is a small mismatch in the names of models downloaded and in the demo codes. It can be easily understood. I just wanted to inform. 
I have a small doubt regarding the generation of **"model.r"** i don't see it anywhere in the code and also in the data loaded from model's pickle file. I can see model.f in pickle file but unclear about model.r object structure. 
Thanks.

**Comment by Rubikplayer** [comment]
Hi, thanks for the feedback.

- For the model filename, I've adjusted the filename in the code and comment. 
- For the "model.r": the model is a 'chumpy' object. When you call ".r", it will evaluate its value (so the return value is a numpy array), equivalent to "model.compute_r()". For details of chumpy, I think it's more clear to check the chumpy code (https://github.com/mattloper/chumpy/blob/master/chumpy/ch.py).

**Comment by thestrawh8** [comment]
Thanks Rubikplayer for explaining in detail.
