### ISSUE TITLE
how to get variance of every shape and expression?

### ISSUE THREAD

**Issue by ZHANG-SHI-CHANG** [Rubikplayer/flame-fitting#11]
hello, i want to know how to get variance of every shape and expression from flame model, i din't find it.

**Comment by scott-vsi** [comment]
Sorry to comment on a closed issue, but did you ever figure this out?

**Comment by scott-vsi** [comment]
For anyone else wondering, see https://github.com/TimoBolkart/TF_FLAME/issues/7
