### ISSUE TITLE
Vertex index of each part

### ISSUE THREAD

**Issue by yilei0620** [Rubikplayer/flame-fitting#12]
Is it possible to provide the list of vertex indices of different parts such as eyes, jaw and head? I want to do it by myself but it will cost a lot of time.

In other words, do you have any suggestions about any convenient methods or tools able to do this?  I will really appreciate it if there is a list provided by project owners. 

Thanks.

**Comment by xianzhongma** [comment]
> Is it possible to provide the list of vertex indices of different parts such as eyes, jaw and head? I want to do it by myself but it will cost a lot of time.
> 
> In other words, do you have any suggestions about any convenient methods or tools able to do this? I will really appreciate it if there is a list provided by project owners.
> 
> Thanks.

Hi, I have the same question with you.  Do you have found the list of index?
