### ISSUE TITLE
does every parameter has specific semantics

### ISSUE THREAD

**Issue by skygoo** [Rubikplayer/flame-fitting#13]
does every expression parameter has its own blendshape expression? such as laugh、wink. 
And I didn't find that the parameter map the eyes, how to close the eye.

**Comment by TimoBolkart** [comment]
The shape and expression parameters correspond to scaled PCA eigenvectors (see the paper for more details). Hence the resulting parameters are without any semantic meaning. One possibility to get semantic control is to label some generated expressions and train a regressor to go from these semantic labels to the FLAME parameters. (Similar to what was done for the human body [bodyvisualizer](http://bodyvisualizer.com/)). 
We have a demo how to change the FLAME expression parameters to get an eye blink in the [VOCA repository](https://github.com/TimoBolkart/voca). I hope this answers your question
