### ISSUE TITLE
Issue with fit_scan.py

### ISSUE THREAD

**Issue by Nishanth009** [Rubikplayer/flame-fitting#17]
Great work. demo fit_scan.py worked well. 
But i have tried fit_scan.py with custom 3d face mesh along with its 3d landmarks. But the output flame model doesn't fitted properly(no errors and optimization completed successfully within 20 sec). The output looks like a general face mesh with no adaptation/similarity to input mesh. Do you have any idea on this. i used pr net face mesh
Thanks

**Comment by TimoBolkart** [comment]
Did you visualize the scan and the fitting in a common viewer (e.g. MeshLab) to ensure that they are in the same local coordinate system. One problem could be that they use different measurement units. FLAME is in Meters, so a scan needs to be brought into the same unit first. (We provide some parameter to indicate the unit of the scan)

**Comment by Nishanth009** [comment]
okay. The landmarks are predicted from image. It is in same scale of input mesh vertex values. Is it possible to use fit_scan with mesh predicted from images like bfm etc.

**Comment by TimoBolkart** [comment]
In principle fit_scan can be used with any kind of unordered point cloud / scan. Only make sure that the scan is in the same unit as the FLAME mesh (i.e. in Meters). If you share the mesh that you want to fit we us, I can have a look at it.

But if your goal is to really convert a BFM mesh to FLAME, you can also try using this [BFM_to_FLAME converter](https://github.com/TimoBolkart/BFM_to_FLAME) instead.

**Comment by Nishanth009** [comment]
Thanks for the reply, I am trying to fit pr net mesh. Not sure how to convert this vertex values into meters 
[3d_mesh_3dlmks.zip](https://github.com/Rubikplayer/flame-fitting/files/5703047/3d_mesh_3dlmks.zip)

**Comment by TimoBolkart** [comment]
You are right, I checked that mesh and it is neither of the units. Here two solutions
1) I just updated `fit_scan.py` for another `scale_unit` option (i.e.` 'NA'`) which will optimize for the right scale. This will allow you to fit the scan.
2) Using PRNet to get a 3D face from an image followed by fitting the mesh with FLAME is possible with option 1 but it is rather inefficient. Instead I recommend using [DECA](https://github.com/YadiraF/DECA) which outputs FLAME meshes and it provides much better shapes than PRNet.

**Comment by Nishanth009** [comment]
Great, i tried the first solution and it is working.
i have one more doubt, is it possible to get the scale parameter of the resultant flame mesh for the image projection. Is it  inherently available in the mesh
Thanks

**Comment by TimoBolkart** [comment]
What do you mean? If you get the scale back that was applied to scale the scan?

**Comment by Nishanth009** [comment]
the scale factor is useful for conversion of units in pixels to flame and vice versa. Thanks.
