### ISSUE TITLE
Fit only shape model and blenshapes

### ISSUE THREAD

**Issue by megahard25** [Rubikplayer/flame-fitting#18]
@TimoBolkart 
Hi! 
I want to use the [eos](https://github.com/patrikhuber/eos) library for my needs using a FLAME model. 
For these purposes it is necessary to get a separate array of shape model with all head models. I mean, for the fit, a basis of 300 head models is used and that is the what I want to get.
It seems that i can get what i need with this code
`all_shapes = model.shapedirs[:,:,0:300]`
This array has shape `(5023, 3, 300)` This should mean that there are 300 models in the array and in each of the model 5023 points. 
But when I try to plot only one model, For example
`all_shapes = model.shapedirs[:,:,0:300]`
`mesh = all_shapes [: , :, 0]`

I am getting the result:
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/47577353/103945888-ea931380-5146-11eb-877d-7d4c2d7c9d39.png">

When I draw the model derived from your example
`model.pose[:]  = np.random.randn(model.pose.size) * 0.02`
`model.betas[:300] = np.random.randn(300) * 0.6`
`model.betas[300:350] = np.random.randn(50) * 0.6`
`mesh = model.r`

Everything works fine
<img width="568" alt="image" src="https://user-images.githubusercontent.com/47577353/103946477-afddab00-5147-11eb-8e64-51504ad35ac1.png">

Please advise how I can achieve the desired result and get an array of 3d models?
Also I really want to understand how I can get eigenvalues, eigenvectors and orthonormal basis? 
Will I be able to get similar objects for blendshapes?

Thank you!!!

**Comment by TimoBolkart** [comment]
The shapedirs of FLAME are vertex offsets from the template as you can see in Eq. 2 of the [FLAME paper](https://ps.is.tuebingen.mpg.de/uploads_file/attachment/attachment/400/paper.pdf). One shapedir alone  (e.g. model.shapedirs[:,:,0])  therefore does not give a valid face. Instead you need to use the shapedir added to the template (e.g. model.template +  model.shapedirs[:,:,0]). This will output a valid face displaced with the first principal component
