### ISSUE TITLE
TF flame-fitting code 

### ISSUE THREAD

**Issue by harrymort** [Rubikplayer/flame-fitting#19]
Hello!! 

I tried to use my 3D scan data(azure kinect dk) to FLAME. However, it takes lots of time.When I check system resource, flame-fitting process is just use CPU core. I want to use GPU to minimize fitting time. So, I wonder you have your flame-fitting code in tensorflow version to use GPU. I already checked other fitting code in TF_FLAME. The mesh fitting code can be adjusted at FLAME 5023 vertices data.  ( https://github.com/TimoBolkart/TF_FLAME : fit_3D_mesh.py )

Thank you.

**Comment by TimoBolkart** [comment]
Hello, right now, we don't have a which is optimized in the scan to mesh distance (i.e. distance that minimizes the difference between all scan vertices and the closest point in the FLAME model's surface) in Tensorflow.
