### ISSUE TITLE
Gaussian distributions and optimization problem

### ISSUE THREAD

**Issue by FLOWERCLOUD** [Rubikplayer/flame-fitting#2]
Hi, thanks for making it open. I wonder if there are Gaussian distributions for the shape parameter , expression paramerter。 The demo you offer just regards them all have the same weight。 
By the way ,when I use FRAME to fit it to 68 landmarks on the 2d landmarks on the picture , it seems that when I use 400 parameter to minimize the fitting energy ,the result is not good. When I use a small set of parameter, the result get better. I realize that  FRAME may work better for point cloud fitting because of more constrains.      Can you give me some idea about how to **optimize it on 2d landmark** ,especially when it invokes expression parameter.

**Comment by Rubikplayer** [comment]
> "If there are Gaussian distribution for shape/expression parameter"

If you mean to ask "if there are Gaussian prior on shape/expression space": Yes, the `shape_err` and `expr_err` are the prior terms. See: 
https://github.com/Rubikplayer/flame-fitting/blob/f0ff5e10f324b2ab19e315be3b96c71863c176af/facefit_lmk3d.py#L59-L61

The parameters are currently set to the same, just for demo. You can also adjust it for your application. 

Using fewer parameters can indeed serve as a regularizer. If that produces better results, then it might show you didn't regularize well when using full parameters. Maybe try to adjust prior weights and add more constraint: landmarks, 3d shapes (as you mentioned, point cloud), texture, etc.

If you have the neutral image for the person, maybe fit to the image using only identity components (and possibly rigid motion). Then for other images with expression, fit pose and expression while keeping identity fixed/heavily regularized.
