### ISSUE TITLE
Problems with fit_scan.py

### ISSUE THREAD

**Issue by sw778** [Rubikplayer/flame-fitting#21]
Hello. Thank you for your great work first of all. 
I want to fit my 3D scan data to the flame model. I first manually marked 51 feature points with MeshLab(the picture above), and after getting the .pp file, I used the load_picked_points function to convert it into an npy file.Then I used the "NA" coordinate system and got the following results(the picture below). I don't know if I did it right.I am wondering if I have to make other changes, or do you have any good suggestions? I have two questions:
1. What is the relationship between scan_lmks.npy and flame_static_embedding.pkl? For example, what is the relationship between the 51 point coordinates in the npy file and the idx 、coords in the pkl file.
2. Do I need to write a flame_static_embedding.pkl corresponding to my own 3D scan data? But I don’t know how to determine the values ​​of lmk_face_idx and lmk_b_coords, what should I do?
Would you clarify more in detail?
![图片1](https://user-images.githubusercontent.com/81848293/128620166-9c521161-b6a1-4b71-8e14-6381e04b1325.png)
![图片2](https://user-images.githubusercontent.com/81848293/128620168-e74e5056-3b48-43b0-9e1e-304cda9f1292.png)

**Comment by TimoBolkart** [comment]
Hi, your landmark oder seems correct, so I guess it is not a problem with the landmarks. What metric unit is your scan in, and what did you specify for the parameter 'scan_unit'? If you don't know the unit, just specify 'NA', then it optimizes for the scale given your provided landmarks.

**Comment by sw778** [comment]
> Hi, your landmark oder seems correct, so I guess it is not a problem with the landmarks. What metric unit is your scan in, and what did you specify for the parameter 'scan_unit'? If you don't know the unit, just specify 'NA', then it optimizes for the scale given your provided landmarks.

Thank you for your reply! As you said, I modified 'scan_lmks.npy', which is the approximate landmark I manually marked.Then I specify 'scan_unit' to "NA", the picture above is the result, but it looks strange.What is the reason for this? Do I need to modify other places, such as 'flame_static_embedding.pkl'? Or need a new landmark marking method?

**Comment by TimoBolkart** [comment]
> > Hi, your landmark oder seems correct, so I guess it is not a problem with the landmarks. What metric unit is your scan in, and what did you specify for the parameter 'scan_unit'? If you don't know the unit, just specify 'NA', then it optimizes for the scale given your provided landmarks.
> 
> Thank you for your reply! As you said, I modified 'scan_lmks.npy', which is the approximate landmark I manually marked.Then I specify 'scan_unit' to "NA", the picture above is the result, but it looks strange.What is the reason for this? Do I need to modify other places, such as 'flame_static_embedding.pkl'? Or need a new landmark marking method?

No, you should never be required to modify files like 'flame_static_embedding.pkl' if you stick to the same landmark order. If you provide me the scan and the landmarks, I can check what is going wrong.

**Comment by sw778** [comment]
> > > Hi, your landmark oder seems correct, so I guess it is not a problem with the landmarks. What metric unit is your scan in, and what did you specify for the parameter 'scan_unit'? If you don't know the unit, just specify 'NA', then it optimizes for the scale given your provided landmarks.
> > 
> > 
> > Thank you for your reply! As you said, I modified 'scan_lmks.npy', which is the approximate landmark I manually marked.Then I specify 'scan_unit' to "NA", the picture above is the result, but it looks strange.What is the reason for this? Do I need to modify other places, such as 'flame_static_embedding.pkl'? Or need a new landmark marking method?
> 
> No, you should never be required to modify files like 'flame_static_embedding.pkl' if you stick to the same landmark order. If you provide me the scan and the landmarks, I can check what is going wrong.

[mesh_3dlmks.zip](https://github.com/Rubikplayer/flame-fitting/files/6953867/mesh_3dlmks.zip)

This is my scan and landmars, I would like to express my sincere thanks to you.

**Comment by TimoBolkart** [comment]
Sorry for the late response, something is wrong with your landmarks. If I visualize them, then there seem to be vertices that map to the back of the head. This messes up the initial scale computation and therefore the result is bad.  I re-clicked the landmarks in your scans, with this landmark files it seems to work. 
[3dlandmarks.zip](https://github.com/Rubikplayer/flame-fitting/files/7009373/3dlandmarks.zip)

You must play a bit with the fitting parameters but I got an ok-ish result then even with the default parameters.

**Comment by sw778** [comment]
It is true that there is a problem with the landmarks map. Now the problem is solved. Thank you very much for your help. 
In addition, if I want these data to bring some expressions, can it be achieved using Flame? Do you have any suggestions? I wish you a happy day.

**Comment by TimoBolkart** [comment]
Sure, just providing an expressive job should do the job. You only need to ensure that you optimize for FLAME's expression and jaw pose parameters as well (which the default setting does). I will close the issue then, given that it is fixed. If there is any other problem, just open a new issue.
