### ISSUE TITLE
How to fitting on BFM07 front face model?

### ISSUE THREAD

**Issue by jinfagang** [Rubikplayer/flame-fitting#25]
Hi, I have a mesh generated from deep3dface reconstruction model. It has texture and a BFM07 face, I want fitting it to FLAME and using the same texture on flame model. Is that possible?

**Comment by TimoBolkart** [comment]
Hi, you can have a look at the (BFM_toFLAME)[https://github.com/TimoBolkart/BFM_to_FLAME] repository. This shows how to get a FLAME mesh from a BFM mesh. It also builds a FLAME texture space with the same parameter control than BFM17.
