### ISSUE TITLE
How to get head geometry as well in flame object

### ISSUE THREAD

**Issue by Suvi-dha** [Rubikplayer/flame-fitting#28]
I have a 3d scan that also has hair geometry over the head. But when converting that scan to Flame, hair geometry and the expressions are lost. Please if you could point out the reason or the solution for the same. Attaching the scan file and the obtained flame obj.
![Screenshot 2022-08-02 at 2 24 34 PM](https://user-images.githubusercontent.com/37800843/182591551-bb5006b1-eff7-4730-8f57-e625631bd708.png)
![Screenshot 2022-08-03 at 4 25 30 PM](https://user-images.githubusercontent.com/37800843/182591687-0418eda8-6e90-46b8-b3f4-0334e7cebd7b.png)

**Comment by TimoBolkart** [comment]
FLAME is trained from scans without such extreme hair and it is therefore not able to describe these. To capture such hair, you would need to add some non-rigid deformation on top of the FLAME mesh, which goes outside the FLAME's model space
