### ISSUE TITLE
Fitting more than 51 landmarks in fit_lmk3d

### ISSUE THREAD

**Issue by ilully0802** [Rubikplayer/flame-fitting#29]
Hi, thanks for your grate jobs! Currently I am testing fitting with 3D landmarks. I have note that it uses 51 landmarks in demo, it works well.How can i extend the number of the landmarks more than 51, expecially landmarks with ears. I have make the pp file using Meshlab, but the result is not good, can you give some advices?Thanks!

**Comment by pfeducode** [comment]
> 嗨，感谢您的出色工作！目前我正在测试与 3D 地标的拟合。我注意到它在演示中使用了 51 个地标，效果很好。如何将地标的数量扩展到 51 个以上，尤其是带有耳朵的地标。我已经用Meshlab制作了pp文件，但是效果不好，可以给点建议吗？谢谢！

excuse me, could you send me a compiled   mesh of plybody.so file. My mesh compilation never passed.Thank you very much

**Comment by ilully0802** [comment]
ok, I have got it, thanks!
