### ISSUE TITLE
How to obtain landmark embedding? 

### ISSUE THREAD

**Issue by Monibsediqi** [Rubikplayer/flame-fitting#31]
Hi, thank you once again for the great work. 
How did you obtain the embedding landmarks for your FLAME model? 
What does the lmk_face_idx mean in embedding landmarks? 
Lastly, utilizing this method can I extend this to fit SMPL model to whole body scan? Like using the joints in the body as an embedding landmark. 
Thank you and waiting for you reply

**Comment by TimoBolkart** [comment]
The landmark embeddings are the barycentric coordinates for each landmark within the FLAME mesh surface. The lmk_face_idx are the indices of the faces (triangles), while the lmk_b_coords are then the weights of the triangle's vertices. (e.g., if `lmk_face_idx = [5,...]` and `lmk_b_coords = [[0.2, 0.3, 0.5],...]` then the first landmark is embedded in the 5th triangle of the FLAME's surface (i.e., `triangle_5 = [v1, v2, v3]`). In this example, you would compute the 3D landmark as `lmk_1 = 0.2*v1 + 0.3*v2 + 0.5*v3).`
