### ISSUE TITLE
ImportError: cannot import name 'sample2meshdist'

### ISSUE THREAD

**Issue by hjo111** [Rubikplayer/flame-fitting#34]
thank you for your great work. 
I got a problem when I run your code. Could you help me with it? Thank you very much.

File "e:\flame-fitting\sbody\alignment\mesh_distance\mesh_distance.py", line 4, in <module>
    from sbody.alignment.mesh_distance import sample2meshdist
ImportError: cannot import name 'sample2meshdist'

**Comment by ryanhg** [comment]
Hey @OKJINHAE what did you do to solve this error? Thanks!

**Comment by 2517722580** [comment]
could you tell me that  what did you do to solve this error? Thanks!

**Comment by 2517722580** [comment]
> @hjo111 Edit the file setup.py to set the **correct** `EIGEN_DIR` to Eigen's location. Then enter：`make`,my `EIGEN_DIR`  is `/usr/include/eigen3`

**Comment by Zvyozdo4ka** [comment]
> > @hjo111 Edit the file setup.py to set the **correct** `EIGEN_DIR` to Eigen's location. Then enter：`make`,my `EIGEN_DIR`  is `/usr/include/eigen3`

I did so, but it just appeared a zillion errors

**Comment by lvZic** [comment]
> > > @hjo111 Edit the file setup.py to set the **correct** `EIGEN_DIR` to Eigen's location. Then enter：`make`,my `EIGEN_DIR`  is `/usr/include/eigen3`
> 
> I did so, but it just appeared a zillion errors

how did u solved it?

**Comment by Zvyozdo4ka** [comment]
> > > > @hjo111 Edit the file setup.py to set the **correct** `EIGEN_DIR` to Eigen's location. Then enter：`make`,my `EIGEN_DIR`  is `/usr/include/eigen3`
> > 
> > 
> > I did so, but it just appeared a zillion errors
> 
> how did u solved it?

i did not solve it

**Comment by lvZic** [comment]
> > > > > @hjo111 Edit the file setup.py to set the **correct** `EIGEN_DIR` to Eigen's location. Then enter：`make`,my `EIGEN_DIR`  is `/usr/include/eigen3`
> > > 
> > > 
> > > I did so, but it just appeared a zillion errors
> > 
> > 
> > how did u solved it?
> 
> i did not solve it

change line 14 to "extra_compile_args += ["-std=c++17"]"

**Comment by Zvyozdo4ka** [comment]
> change line 14 to "extra_compile_args += ["-std=c++17"]"

in which file?

**Comment by lvZic** [comment]
> Referen

 setup.py
