### ISSUE TITLE
[Question] landmarks order in lmk_3d 

### ISSUE THREAD

**Issue by AviP1234** [Rubikplayer/flame-fitting#4]
Hi, thank you very much for sharing your great work.
I have a question about the input format:
In lmk_3d what are the order of the landmarks in the array?
Do lmk_3d[0] is landmark 17 in the image, then lmk_3d[1] is  landmark 18 ext.?
Thank you,
Avi
![68blank](https://user-images.githubusercontent.com/31180090/44790959-39a90100-aba9-11e8-8425-448561070e8a.png)

**Comment by Rubikplayer** [comment]
Hi @AviP1234,

Your landmark mapping seems mostly the same as the my (actually intraface) mapping: e.g. lmk_3d[0] is your landmark 17. However, for mouth region, I'm not sure where 60 and 64 are mapping to. You can check the following image for intraface landmark mapping.

![front-frace-intra-face-landmarks-01](https://user-images.githubusercontent.com/5596684/44829283-cf0bbb80-abd0-11e8-808f-1f3e950e46f5.jpg)

**Comment by AviP1234** [comment]
Thank you!

**Comment by AviP1234** [comment]
Thank you. 
I have another question: what are: lmk_face_idx, lmk_b_coords?
Are they the same as for all images?

**Comment by Rubikplayer** [comment]
@AviP1234 

`lmk_face_idx` stores which triangle on flame template mesh corresponds to an intraface landmark.
`lmk_b_coords` stores the barycentric coordinate for that intraface landmark.
This can be regarded as a "finer" landmark correspondence, compared to just vertex indices. They should work for all images.

**Comment by Rubikplayer** [comment]
This issue is now closed. Thanks for the question.

**Comment by wwdok** [comment]
@Rubikplayer Do you konw how to control the number of fitting steps, i run `python fit_lmk3d.py` with default setting, it outputs :

```
loaded 3d landmark from: ./data/scan_lmks.npy
loaded model from: ./models/generic_model.pkl
loaded lmk embedding
fit_lmk3d(): use the following weights:
fit_lmk3d(): weights['lmk'] = 1.000000
fit_lmk3d(): weights['shape'] = 0.001000
fit_lmk3d(): weights['expr'] = 0.001000
fit_lmk3d(): weights['pose'] = 0.010000

step 1: start rigid fitting...
2.30e-02
9.52e-04
9.51e-04
9.51e-04
step 1: fitting done, in 0.560500 sec

step 2: start non-rigid fitting...
9.51e-04 | expr: 0.00e+00 | lmk: 9.51e-04 | pose: 0.00e+00 | shape: 0.00e+00
8.23e-04 | expr: 3.34e-09 | lmk: 8.23e-04 | pose: 1.02e-07 | shape: 5.64e-09
7.71e-04 | expr: 4.41e-08 | lmk: 7.71e-04 | pose: 1.07e-07 | shape: 7.47e-08
7.13e-04 | expr: 3.48e-07 | lmk: 7.12e-04 | pose: 1.30e-07 | shape: 5.92e-07
5.89e-04 | expr: 2.36e-06 | lmk: 5.82e-04 | pose: 2.41e-07 | shape: 4.05e-06
4.07e-04 | expr: 1.51e-05 | lmk: 3.65e-04 | pose: 8.27e-07 | shape: 2.63e-05
3.83e-04 | expr: 2.56e-05 | lmk: 3.10e-04 | pose: 1.15e-06 | shape: 4.61e-05
3.83e-04 | expr: 2.54e-05 | lmk: 3.10e-04 | pose: 1.11e-06 | shape: 4.62e-05
step 2: fitting done, in 17.043893 sec
```

It seems the rigid fitting takes  4 steps, no-rigid fitting takes 8 steps. Because i see the fitted `fit_lmk3d_result.obj` is not good, so i want to increase the fitting steps, how to do that ?
