### ISSUE TITLE
Increasing the number of points and getting static and dynamic landmark embeddings.

### ISSUE THREAD

**Issue by filby89** [Rubikplayer/flame-fitting#40]
Hi, thank you very much for your repo!
I would like to ask is you have any specific process for getting the static barycentric coordinates, as well as the dynamic landmark embeddings, in case someone wants to add more keypoints.

**Comment by TimoBolkart** [comment]
To get specific landmark embeddings, we render faces in FLAME topology of different face shapes from varying angles, run the 2D landmark predictors, and project  those landmarks on the 3D mesh. Then, we average the landmark locations across the different face shapes, and compute its barycentric embedding. Sharing this pipeline would require some cleanup that I am unable to do right now, but we do have embeddings for instance for around 100 Mediapipe keypoints. We could share this if this would help.

**Comment by filby89** [comment]
Thanks, I think I got it! It would be great if you could share the mentioned embeddings for mediapipe kps (and which kps are those). I have generally seen that an increasing number of repos are switching to mediapipe from FAN.

**Comment by TimoBolkart** [comment]
Makes sense, Mediapipe is more accurate around the eyes and the lips than FAN. You find the landmark embeddings [here](https://files.is.tue.mpg.de/tbolkart/FLAME/mediapipe_landmark_embedding.zip). I also added them to the FLAME download page.

**Comment by filby89** [comment]
Great, thanks again !

**Comment by ArjunZ786** [comment]
sorry dumb question, what does FAN stand for?

**Comment by akasharidas** [comment]
@TimoBolkart The mediapipe embeddings you provided are helpful, but they only contain keypoints around the eyes, nose and lips. I'm trying to add more keypoints especially around the edges of the face or on the contour. If you have code already for the pipeline you mentioned for adding more keypoints, could you please share it?

**Comment by shunlinlu** [comment]
Hi, @akasharidas 

Did you solve it?
