### ISSUE TITLE
Mediapipe embeddings 

### ISSUE THREAD

**Issue by ankarako** [Rubikplayer/flame-fitting#44]
Hey there,  

Thank you very much for your work all these years! 
I would like to ask about FLAME's mediapipe embeddings. Mediapipe's face mesh detection (and face landmark detection) outputs 474 landmarks. FLAME's mediapipe embeddings provide 105 landmarks. Is there any correspondence between those two?

Thanks for your time

**Comment by TimoBolkart** [comment]
Hello, the Mediapipe FLAME embedding file also contains an index list with 105 integers. These tell you, which 105 of the 474 Mediapipe landmarks, and in which order we consider as valid subset

**Comment by ankarako** [comment]
Great! I didn't realize that. thank you very much!

**Comment by Sonal-Monteiro** [comment]
> Hello, the Mediapipe FLAME embedding file also contains an index list with 105 integers. These tell you, which 105 of the 474 Mediapipe landmarks, and in which order we consider as valid subset

Could you please share a link to this index list? I am not able to find it.
Thanks

**Comment by ankarako** [comment]
You can download it from the official FLAME release [website](https://flame.is.tue.mpg.de/).

**Comment by NiranjanV123** [comment]
> You can download it from the official FLAME release [website](https://flame.is.tue.mpg.de/).

Can you specify exact link to the file?
 Thanks.

**Comment by ankarako** [comment]
You must register for the downloads page to become available

**Comment by camille-dupont** [comment]
Hi I'm trying to use Mediapipe to animate a flame model and I don't realy understand how mediapipe embeddings works and how to use it with pose, shape and expression param.

**Comment by lyxcc127** [comment]
FLAME's mediapipe embed has no face contour, anyone know the correspondence?
