### ISSUE TITLE
using load_model in smpl_webuser.serialization

### ISSUE THREAD

**Issue by sidis8066** [Rubikplayer/flame-fitting#5]
i want to save obj file into pickle.guide me to use from smpl_webuser.serialization import save_model.
How can i read model file 
i am using python2.7 ubuntu16.04

**Comment by Rubikplayer** [comment]
To read model file, in `hello_world.py` there is an example to read model and save a result mesh into obj file. 
https://github.com/Rubikplayer/flame-fitting/blob/f0ff5e10f324b2ab19e315be3b96c71863c176af/hello_world.py#L20

To save obj file into pickle, you can try this function:
https://github.com/Rubikplayer/flame-fitting/blob/f0ff5e10f324b2ab19e315be3b96c71863c176af/fitting/util.py#L19
