### ISSUE TITLE
how to crop Flame model？

### ISSUE THREAD

**Issue by KangolHsu** [Rubikplayer/flame-fitting#6]
thanks for your model！i want to crop face from FLAME，and use it like sfm bfm...。Is this possible，and could you give me some advice？

**Comment by KangolHsu** [comment]
One more question, only 3d landmark detector  is worked or not?

**Comment by Rubikplayer** [comment]
To crop the face mesh, you can try manually cut the mesh using Meshlab, Blender, Maya or other 3D tools. You only need to do this once. After that, you can apply the same vertices and faces selection to all FLAME-generated face meshes.

For your second question, I don't fully understand. Could you clarify?
