### ISSUE TITLE
How can i transfer the facial expression from a source actor to a target actor?

### ISSUE THREAD

**Issue by zheLim** [Rubikplayer/flame-fitting#7]
Thanks for you great work. FLAME performs well.
May i know how to transfer the facial expression from a source actor to a target actor?
It seems that code on repository  do not contain such function.

**Comment by mrgloom** [comment]
Isn't it possible to just replace `shape (identity) coefficients` and generate new shape?
https://github.com/Rubikplayer/flame-fitting/blob/master/hello_world.py#L25

**Comment by zheLim** [comment]
> Isn't it possible to just replace `shape (identity) coefficients` and generate new shape?
> https://github.com/Rubikplayer/flame-fitting/blob/master/hello_world.py#L25

I see, thanks a lot!
BTW, do you know how to do FACE REGISTRATION?

**Comment by mrgloom** [comment]
I'm not sure if statement `just replace shape (identity) coefficients and generate new shape` is true, in [paper](https://www.is.mpg.de/uploads_file/attachment/attachment/400/paper.pdf) section `7.5    Expression transfer` they claim that average model template should be replaced to change person identity, I'm not sure if this average template should be computed from sequence of 3d scans or can be computed just by single scan.

Regarding 3D face alignment you can use ICP or some non rigid version of ICP for pair of 3D scans, but for 4D I don't know the solution.

**Comment by zheLim** [comment]
@mrgloom It seems that the only way to figure it out is giving it a try. Thanks for your kindly reply!

**Comment by TimoBolkart** [comment]
@mrgloom You are right, for transferring expression (and pose) between subjects, we usually replace the average template by a template specific to the target subject. We usually compute such a template by aligning (i.e. using coupled single frame alignment as described in the paper) for a single frame in neutral expression. Please be aware that after fitting the neutral scan, in oder to qualify for being used as a template, one needs to bring the mesh into "zero pose" by undoing the translation and pose variation.

**Comment by zheLim** [comment]
@TimoBolkart Will you provide code for REGISTRATION?

**Comment by TimoBolkart** [comment]
We have code available to fit FLAME to images, 3D landmarks, and to 3D meshes in FLAME topology. We also have multiple face datasets available with registrations in FLAME topology such as [registered D3DFACS](flame.is.tue.mpg.de), [CoMA dataset](https://coma.is.tue.mpg.de/), and [VOCASET](https://voca.is.tue.mpg.de/). To date, we do not have any publicly available scan registration method.

**Comment by kuangcy1998** [comment]
@TimoBolkart  Thanks for your great work! Could you provide codes to fit FLAME to images and 3D meshes? It seems only fitting to 3D landmarks are provided.
