### ISSUE TITLE
Given aligned shape model is it possible to project face texture from image to model?

### ISSUE THREAD

**Issue by mrgloom** [Rubikplayer/flame-fitting#8]
Given aligned (to 2d image) shape model is it possible to project face texture from image to model?
Also does FLAME model contain some texture basis?

**Comment by TimoBolkart** [comment]
Yes, if you have a 3D FLAME mesh aligned with an image (e.g. obtained by fitting FLAME to an image or using RingNet), one can project the texture onto the 3D face mesh.
FLAME does not provide a texture space to date, but we plan to provide some texture model for it in the future

**Comment by mrgloom** [comment]
Does current code have this texture projection implemented? if not how it's called more precisely?
What is `texture space to date`, do you mean some texture basis? as I understand FLAME doesn't have it.

**Comment by TimoBolkart** [comment]
The current code does not provide such a texture projection, but one can potentially use Neural Mesh Renderer to compute a texture

**Comment by mrgloom** [comment]
I.e. it can't be done in pure compute graphics / photogrammetry?

**Comment by TimoBolkart** [comment]
Sure, this is just a projection of an image onto a mesh. I am just not aware of ready to use publicly available code that just does this, even though it is widely used

**Comment by TimoBolkart** [comment]
I added a demo to the [TF_FLAME](https://github.com/TimoBolkart/TF_FLAME) repository to project an image onto a fitted FLAME mesh.
